version: '3'

services:
  product-service:
    build: ./LLaVA
    volumes:
      - ./LLaVA:/LLaVA
    ports: 
      - 5002:80
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]